//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Del
{
    using System;
    using System.Collections.Generic;
    
    public partial class customercode
    {
        public customercode()
        {
            this.eorder = new HashSet<eorder>();
            this.invtitlecode1 = new HashSet<invtitlecode>();
        }
    
        public long cusID { get; set; }
        public string cusAcc { get; set; }
        public Nullable<short> cusKind { get; set; }
        public string tel { get; set; }
        public string simpleComany { get; set; }
        public string cusName { get; set; }
        public string cusPws { get; set; }
        public string companyName { get; set; }
        public string contactName { get; set; }
        public string tax { get; set; }
        public string zip { get; set; }
        public string companyAddress { get; set; }
        public string sendAddress { get; set; }
        public string taxAddress { get; set; }
        public string cusEmail { get; set; }
        public Nullable<short> payID { get; set; }
        public Nullable<short> invTitleCode { get; set; }
        public string contactMobile { get; set; }
        public Nullable<System.DateTime> buildDate { get; set; }
        public string cusMemo { get; set; }
        public Nullable<int> cClerk { get; set; }
        public string rutenId { get; set; }
    
        public virtual ICollection<eorder> eorder { get; set; }
        public virtual ICollection<invtitlecode> invtitlecode1 { get; set; }
    }
}
