//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Del
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class inikierpEntities : DbContext
    {
        public inikierpEntities()
            : base("name=inikierpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<customercode> customercode { get; set; }
        public DbSet<eorder> eorder { get; set; }
        public DbSet<eorderitem> eorderitem { get; set; }
        public DbSet<invoice> invoice { get; set; }
        public DbSet<invtitlecode> invtitlecode { get; set; }
        public DbSet<paywaycode> paywaycode { get; set; }
        public DbSet<productcode> productcode { get; set; }
        public DbSet<sendcode> sendcode { get; set; }
    }
}
