//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Del
{
    using System;
    using System.Collections.Generic;
    
    public partial class eorderitem
    {
        public long odID { get; set; }
        public long odItemID { get; set; }
        public Nullable<long> invi { get; set; }
        public long prodID { get; set; }
        public string disCount { get; set; }
        public Nullable<double> qty { get; set; }
        public string iunitDesc { get; set; }
        public Nullable<double> unitPrice { get; set; }
        public string isValue { get; set; }
        public Nullable<long> oldItemPrID { get; set; }
        public Nullable<System.DateTime> deliveryDate { get; set; }
        public string note { get; set; }
        public Nullable<bool> isPrint { get; set; }
    
        public virtual eorder eorder { get; set; }
        public virtual productcode productcode { get; set; }
    }
}
